_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 17
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
ADACONTRAST:
    value:
        ALPHA: 1
        BETA: 1
        CE_SUP_TYPE: weak_strong
        CE_TYPE: standard
        CONTRAST_TYPE: class_aware
        DIST_TYPE: cosine
        ETA: 1
        NUM_NEIGHBORS: 10
        QUEUE_SIZE: 16384
        REFINE_METHOD: nearest_neighbors
BN:
    value:
        ALPHA: 0.1
CKPT_DIR:
    value: ./ckpt
CLIP:
    value:
        FREEZE_TEXT_ENCODER: true
        PRECISION: fp16
        PROMPT_MODE: custom
        PROMPT_PATH: datasets/cupl_prompts/CuPL_ImageNet_prompts.json
        PROMPT_TEMPLATE:
            - a photo of a {}.
CMF:
    value:
        ALPHA: 0.99
        GAMMA: 0.99
        Q: 0.005
        TYPE: lp
CONTRAST:
    value:
        MODE: all
        PROJECTION_DIM: 128
        TEMPERATURE: 0.1
CORRUPTION:
    value:
        DATASET: cifar10_c
        NUM_EX: -1
        SEVERITY:
            - 5
        TYPE:
            - gaussian_noise
            - shot_noise
            - impulse_noise
            - defocus_blur
            - glass_blur
            - motion_blur
            - zoom_blur
            - snow
            - frost
            - fog
            - brightness
            - contrast
            - elastic_transform
            - pixelate
            - jpeg_compression
COTTA:
    value:
        AP: 0.92
        RST: 0.01
CUDNN:
    value:
        BENCHMARK: true
DATA_DIR:
    value: ./data
DESC:
    value: ""
DETERMINISM:
    value: false
DEYO:
    value:
        AUG_TYPE: patch
        COLUMN_START: 56
        MARGIN: 0.5
        OCCLUSION_SIZE: 112
        PATCH_LEN: 4
        PLPD: 0.2
        REWEIGHT_ENT: true
        REWEIGHT_PLPD: true
        ROW_START: 56
EATA:
    value:
        D_MARGIN: 0.05
        FISHER_ALPHA: 2000
        MARGIN_E0: 0.4
GTTA:
    value:
        LAMBDA_MIXUP: 0.3333333333333333
        PRETRAIN_STEPS_ADAIN: 20000
        STEPS_ADAIN: 1
        USE_STYLE_TRANSFER: false
LAME:
    value:
        AFFINITY: rbf
        FORCE_SYMMETRY: false
        KNN: 5
        SIGMA: 1
LOG_DEST:
    value: tent_250119_104829.txt
LOG_TIME:
    value: "250119_104829"
M_TEACHER:
    value:
        MOMENTUM: 0.999
MIXED_PRECISION:
    value: false
MODEL:
    value:
        ADAPTATION: tent
        ARCH: Standard
        CKPT_PATH: ""
        EPISODIC: false
        RESET_AFTER_NUM_UPDATES: 0
        USE_CLIP: false
        WEIGHTS: IMAGENET1K_V1
OPTIM:
    value:
        BETA: 0.9
        DAMPENING: 0
        LR: 0.001
        METHOD: Adam
        MOMENTUM: 0.9
        NESTEROV: true
        STEPS: 1
        WD: 0
Ours:
    value:
        LOSSES:
            - ce_s_t1
            - ce_s_t2
            - ce_s_aug_t1
            - contr_t2_proto
            - mse_t2_proto
            - contr_t2
            - im_loss
            - differ_loss
            - l2_sp
            - kld_t2_proto
PRINT_EVERY:
    value: -1
RMT:
    value:
        LAMBDA_CE_SRC: 1
        LAMBDA_CE_TRG: 1
        LAMBDA_CONT: 1
        NUM_SAMPLES_WARM_UP: 50000
RNG_SEED:
    value: 1
ROID:
    value:
        MOMENTUM_PROBS: 0.9
        MOMENTUM_SRC: 0.99
        TEMPERATURE: 0.3333333333333333
        USE_CONSISTENCY: true
        USE_PRIOR_CORRECTION: true
        USE_WEIGHTING: true
ROTTA:
    value:
        ALPHA: 0.05
        LAMBDA_T: 1
        LAMBDA_U: 1
        MEMORY_SIZE: 64
        NU: 0.001
        UPDATE_FREQUENCY: 64
RPL:
    value:
        Q: 0.8
SANTA:
    value:
        LAMBDA_CE_TRG: 1
        LAMBDA_CONT: 1
SAR:
    value:
        RESET_CONSTANT_EM: 0.2
SAVE_DIR:
    value: ./output/tent_cifar10_c_250119_104829
SETTING:
    value: continual
SOURCE:
    value:
        NUM_SAMPLES: -1
        NUM_WORKERS: 4
        PERCENTAGE: 1
TEST:
    value:
        BATCH_SIZE: 200
        DEBUG: false
        DELTA_DIRICHLET: 0
        N_AUGMENTATIONS: 32
        NUM_WORKERS: 4
        WINDOW_LENGTH: 1
TPT:
    value:
        CLASS_TOKEN_POS: end
        CTX_INIT: a_photo_of_a
        N_CTX: 4
        SELECTION_P: 0.1
fed:
    value:
        fed_tech: none_fed
